# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows/ConnectingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectingWindow(object):
    def setupUi(self, ConnectingWindow):
        ConnectingWindow.setObjectName("ConnectingWindow")
        ConnectingWindow.resize(403, 188)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("windows/../images/quad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConnectingWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ConnectingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.parameterProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.parameterProgressBar.setGeometry(QtCore.QRect(10, 100, 381, 23))
        self.parameterProgressBar.setProperty("value", 24)
        self.parameterProgressBar.setObjectName("parameterProgressBar")
        self.connectingLabel = QtWidgets.QLabel(self.centralwidget)
        self.connectingLabel.setGeometry(QtCore.QRect(50, 20, 291, 61))
        self.connectingLabel.setObjectName("connectingLabel")
        ConnectingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConnectingWindow)
        self.statusbar.setObjectName("statusbar")
        ConnectingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConnectingWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectingWindow)

    def retranslateUi(self, ConnectingWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectingWindow.setWindowTitle(_translate("ConnectingWindow", "Bağlantı Kuruluyor"))
        self.connectingLabel.setText(_translate("ConnectingWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConnectingWindow = QtWidgets.QMainWindow()
    ui = Ui_ConnectingWindow()
    ui.setupUi(ConnectingWindow)
    ConnectingWindow.show()
    sys.exit(app.exec_())
