# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows/WaypointWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaypointWindow(object):
    def setupUi(self, WaypointWindow):
        WaypointWindow.setObjectName("WaypointWindow")
        WaypointWindow.resize(1939, 1040)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("windows/../images/quad.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WaypointWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WaypointWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 40, 1731, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mapCLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mapCLayout.setContentsMargins(0, 0, 0, 0)
        self.mapCLayout.setObjectName("mapCLayout")
        self.coordinateWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.coordinateWidget.setGeometry(QtCore.QRect(330, 830, 671, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinateWidget.sizePolicy().hasHeightForWidth())
        self.coordinateWidget.setSizePolicy(sizePolicy)
        self.coordinateWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.coordinateWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.coordinateWidget.setObjectName("coordinateWidget")
        self.coordinateWidget.setColumnCount(3)
        self.coordinateWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.coordinateWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.coordinateWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.coordinateWidget.setHorizontalHeaderItem(2, item)
        self.coordinateWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.coordinateWidget.horizontalHeader().setSortIndicatorShown(False)
        self.coordinateWidget.horizontalHeader().setStretchLastSection(False)
        self.coordinateWidget.verticalHeader().setVisible(True)
        self.coordinateWidget.verticalHeader().setCascadingSectionResizes(False)
        self.yukleButton = QtWidgets.QPushButton(self.centralwidget)
        self.yukleButton.setGeometry(QtCore.QRect(1050, 920, 141, 41))
        self.yukleButton.setStyleSheet("background-color: rgb(55, 255, 0)")
        self.yukleButton.setObjectName("yukleButton")
        self.okuButton = QtWidgets.QPushButton(self.centralwidget)
        self.okuButton.setGeometry(QtCore.QRect(1050, 860, 141, 41))
        self.okuButton.setStyleSheet("background-color: rgb(255, 254, 8)")
        self.okuButton.setObjectName("okuButton")
        WaypointWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WaypointWindow)
        QtCore.QMetaObject.connectSlotsByName(WaypointWindow)

    def retranslateUi(self, WaypointWindow):
        _translate = QtCore.QCoreApplication.translate
        WaypointWindow.setWindowTitle(_translate("WaypointWindow", "QUADRUPLET - Waypoint"))
        item = self.coordinateWidget.horizontalHeaderItem(0)
        item.setText(_translate("WaypointWindow", "Lat"))
        item = self.coordinateWidget.horizontalHeaderItem(1)
        item.setText(_translate("WaypointWindow", "Long"))
        item = self.coordinateWidget.horizontalHeaderItem(2)
        item.setText(_translate("WaypointWindow", "Alt"))
        self.yukleButton.setText(_translate("WaypointWindow", "Yükle"))
        self.okuButton.setText(_translate("WaypointWindow", "Oku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaypointWindow = QtWidgets.QMainWindow()
    ui = Ui_WaypointWindow()
    ui.setupUi(WaypointWindow)
    WaypointWindow.show()
    sys.exit(app.exec_())
