# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows/WaypointsSettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaypointsSettingWindow(object):
    def setupUi(self, WaypointsSettingWindow):
        WaypointsSettingWindow.setObjectName("WaypointsSettingWindow")
        WaypointsSettingWindow.resize(403, 188)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("windows/../images/quad.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WaypointsSettingWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WaypointsSettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settingProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.settingProgressBar.setGeometry(QtCore.QRect(10, 100, 381, 23))
        self.settingProgressBar.setProperty("value", 24)
        self.settingProgressBar.setObjectName("settingProgressBar")
        self.settingLabel = QtWidgets.QLabel(self.centralwidget)
        self.settingLabel.setGeometry(QtCore.QRect(110, 20, 231, 61))
        self.settingLabel.setObjectName("settingLabel")
        WaypointsSettingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WaypointsSettingWindow)
        self.statusbar.setObjectName("statusbar")
        WaypointsSettingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WaypointsSettingWindow)
        QtCore.QMetaObject.connectSlotsByName(WaypointsSettingWindow)

    def retranslateUi(self, WaypointsSettingWindow):
        _translate = QtCore.QCoreApplication.translate
        WaypointsSettingWindow.setWindowTitle(_translate("WaypointsSettingWindow", "Waypoint\'ler ayarlanıyor"))
        self.settingLabel.setText(_translate("WaypointsSettingWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaypointsSettingWindow = QtWidgets.QMainWindow()
    ui = Ui_WaypointsSettingWindow()
    ui.setupUi(WaypointsSettingWindow)
    WaypointsSettingWindow.show()
    sys.exit(app.exec_())
